name: RAG Automation Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened]
  pull_request:
    types: [opened, synchronize]

jobs:
  patch-and-validate:
    name: Generate & Apply Patch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker container
        run: docker build -t rag-runner -f automation/Dockerfile .

      - name: Run patch generator inside Docker
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          docker run --rm \
            -e OPENAI_API_KEY \
            -e GITHUB_TOKEN \
            -e GITHUB_REPO \
            rag-runner python change_applier.py

  review-pr:
    name: Review Pull Request
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run PR reviewer
        working-directory: automation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
        run: python pr_reviewer.py
