name: RAG Automation Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened]
  pull_request:
    types: [opened, synchronize]

jobs:
  patch-and-validate:
    name: Generate & Apply Patch
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          apt-get update
          apt-get install -y git curl
          pip install --upgrade pip
          pip install openai requests llm-prompt-semantic-diff pytest flake8

      - name: Run patch generator
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          python issue_handler.py
          python change_applier.py

  review-pr:
    name: Review Pull Request
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run PR reviewer
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
        run: python pr_reviewer.py
